title: <p align="center"> Soumit Sarkar </p>
logo: /assets/img/photo.jpg

description:
  <p align="center">
  Data Science |
  Machine Learning |
  Generative AI
 
  <br>  
  I am a Data Science enthusiast
  <br>
  </p>



theme: jekyll-theme-minimal
